version: '3'
services:
  lego-mongo:
    image: mongo
    container_name: lego-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - '$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/'
    ports:
      - 27018:27017
    env_file:
      - .env
  lego-redis:
    image: redis
    container_name: lego-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6378:6379
    env_file:
      - .env
  lego-serve:
    depends_on:
      - lego-mongo
      - lego-redis
    build:
      context: . # 当前目录
      dockerfile: Dockerfile # 基于Dockerfile构建
    image: registry.cn-hangzhou.aliyuncs.com/jimmymute/lego:{{tag}}
    container_name: lego-serve
    ports:
      - 7001:7001
    env_file:
      - .env
